### PR TITLE
JS files can be hot reloaded now

### PR DESCRIPTION
**Pull request by capaj**
when a JS file changes, we reload just the affected dependency tree branch, nothing more. Much faster than whole page refresh.

### CODE REVIEW

**Comment by jimthedev** [comment]
Does this get you the same functionality as, say, react-hot-loader but in ng2?

**Comment by gdi2290** [comment]
@jimthedev this is the Angular 1 starter for the jspm branch

**Comment by jimthedev** [comment]
Ohhhhh. 😜 Woops

**Comment by gdi2290** [comment]
LGTM, @danthareja can you review

**Comment by capaj** [comment]
@jimthedev I can plug it into your favourite angular2 boilerplate if it uses JSPM and ES6 modules. Just give me a link

**Comment by danthareja** [comment]
this is a huge win for JSPM! Thanks @capaj!

**Comment by capaj** [comment]
@danthareja yeah I was surprised to see how well it performs. Also we should upgrade to https://github.com/capaj/jspm-hot-reloader/releases/tag/0.1.4 immediatelly. In 0.1.2 when you made a syntax error, you had to correct it and manually reload. This has been fixed.

**Comment by danthareja** [comment]
@capaj can you make another PR for this? Also, if you're still actively developing this feature, would it make sense to hold off on merging this until it is more stable?

**Comment by capaj** [comment]
@danthareja I want to investigate and maybe add one more feature-support for commonjs modules. Then I will release 1.0.0. So I think it is ready now for other developers to start using it even on mission critical projects. I know I do.

**Comment by gdi2290** [comment]
let's keep it in and make PRs as you go since this helps jspm

related [tweet](https://twitter.com/AngularClass/status/653985300855676928)

**Comment by danthareja** [comment]
:+1:

**Pull request merged**
